title: KickAss101
email: jaswanthsunkara@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Writeups/Walkthroughs for n00bs by a n00b :)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kickass101.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: KickAss101_
github_username: KickAss101
author: KickAss101

github:
  repository_url: https://github.com/KickAss101

# Build settings
theme: jekyll-theme-hacker